In [2]:
# importação de Bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from glob import glob

In [3]:
df1 = pd.read_csv('dados/bdqueimadas_2016-01-01_2016-03-07.csv', sep = ',')

In [4]:
df1.head()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2016/01/01 00:00:00,GOES-13,Brasil,PARÁ,BRASIL NOVO,Amazônia,7,8.3,0.8,NaN,-2.95,-52.33
1,2016/01/01 00:00:00,GOES-13,Brasil,RONDÔNIA,CACOAL,Amazônia,0,10.6,0.1,NaN,-11.34,-61.10
2,2016/01/01 00:00:00,GOES-13,Brasil,PARÁ,VITÓRIA DO XINGU,Amazônia,7,7.6,0.5,NaN,-2.95,-52.31
3,2016/01/01 00:00:00,GOES-13,Brasil,RONDÔNIA,CACOAL,Amazônia,0,13.1,0.1,NaN,-11.34,-61.13
4,2016/01/01 00:00:00,GOES-13,Brasil,AMAZONAS,BARCELOS,Amazônia,3,0.0,0.9,NaN,0.50,-63.68

In [5]:
df2 = pd.read_csv('dados/bdqueimadas_2016-03-08_2017-03-08.csv', sep = ',')

In [6]:
df2.head()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2016/03/08 00:30:00,GOES-13,Brasil,AMAZONAS,BARCELOS,Amazônia,2,2.2,0.4,NaN,0.070,-62.620
1,2016/03/08 00:30:00,GOES-13,Brasil,AMAZONAS,BARCELOS,Amazônia,3,1.4,0.6,NaN,0.070,-62.640
2,2016/03/08 01:30:00,GOES-13,Brasil,PARANÁ,JESUÍTAS,Mata Atlântica,6,0.0,0.6,NaN,-24.530,-53.380
3,2016/03/08 01:43:00,TERRA_M-M,Brasil,SÃO PAULO,BEBEDOURO,Mata Atlântica,0,0.0,0.2,4.2,-20.997,-48.615
4,2016/03/08 01:43:00,TERRA_M-M,Brasil,PARANÁ,RONDON,Mata Atlântica,5,1.0,0.4,14.8,-23.417,-52.687

In [7]:
df3 = pd.read_csv('dados/bdqueimadas_2017-03-09_2018-03-09.csv', sep = ',')

In [8]:
df3.head()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2017/03/09 00:15:00,METOP-B,Brasil,MINAS GERAIS,CAPELINHA,Mata Atlântica,0,0.0,0.1,NaN,-17.6322,-42.292900
1,2017/03/09 00:15:00,METOP-B,Brasil,BAHIA,ITABELA,Mata Atlântica,0,0.0,1.0,NaN,-16.6595,-39.580399
2,2017/03/09 00:15:00,METOP-B,Brasil,ALAGOAS,CORURIPE,Mata Atlântica,0,0.0,1.0,NaN,-9.9879,-36.243599
3,2017/03/09 00:15:00,METOP-B,Brasil,ALAGOAS,CORURIPE,Mata Atlântica,0,0.0,1.0,NaN,-9.9781,-36.245899
4,2017/03/09 00:15:00,METOP-B,Brasil,BAHIA,SAÚDE,Caatinga,0,0.4,1.0,NaN,-10.7989,-40.403099

In [9]:
df4 = pd.read_csv('dados/bdqueimadas_2018-03-10_2019-03-10.csv', sep = ',')

In [10]:
df4.head()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2018/03/10 00:04:24,GOES-16,Brasil,ALAGOAS,CORURIPE,Mata Atlântica,0,0.0,1.0,NaN,-10.060000,-36.200000
1,2018/03/10 00:04:24,GOES-16,Brasil,ALAGOAS,CORURIPE,Mata Atlântica,0,0.0,1.0,NaN,-10.060000,-36.180000
2,2018/03/10 00:20:33,GOES-16,Brasil,RORAIMA,RORAINÓPOLIS,Amazônia,0,0.0,0.4,NaN,0.620000,-60.520000
3,2018/03/10 00:42:40,METOP-B,Brasil,SÃO PAULO,ANGATUBA,Cerrado,0,0.0,0.3,NaN,-23.284401,-48.411900
4,2018/03/10 00:43:13,METOP-B,Brasil,SÃO PAULO,MONTE ALTO,Cerrado,0,2.5,0.3,NaN,-21.279400,-48.584099

In [11]:
df5 = pd.read_csv('dados/bdqueimadas_2019-03-11_2020-03-11.csv', sep = ',')

In [12]:
df5.head()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2019/03/11 00:05:36,GOES-16,Brasil,RORAIMA,CARACARAÍ,Amazônia,38,3.3,1.0,NaN,1.08,-60.73
1,2019/03/11 00:05:36,GOES-16,Brasil,RORAIMA,SÃO JOÃO DA BALIZA,Amazônia,21,2.4,1.0,NaN,1.08,-59.80
2,2019/03/11 00:05:36,GOES-16,Brasil,RORAIMA,CARACARAÍ,Amazônia,43,3.1,1.0,NaN,1.06,-60.80
3,2019/03/11 00:05:36,GOES-16,Brasil,RORAIMA,CARACARAÍ,Amazônia,36,3.6,0.9,NaN,1.06,-60.73
4,2019/03/11 00:05:36,GOES-16,Brasil,RORAIMA,CARACARAÍ,Amazônia,43,2.8,1.0,NaN,1.10,-60.76

In [13]:
df6 = pd.read_csv('dados/bdqueimadas_2020-03-12_2021-03-12.csv', sep = ',')

In [14]:
df6.head()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2020/03/12 00:03:05,GOES-16,Brasil,SÃO PAULO,BOTUCATU,Cerrado,15,0.0,0.7,NaN,-22.71,-48.40
1,2020/03/12 00:03:11,GOES-16,Brasil,MATO GROSSO DO SUL,PORTO MURTINHO,Pantanal,21,0.0,0.7,NaN,-21.42,-57.89
2,2020/03/12 00:03:15,GOES-16,Brasil,MATO GROSSO DO SUL,BONITO,Cerrado,15,0.0,0.8,NaN,-20.92,-56.32
3,2020/03/12 00:03:17,GOES-16,Brasil,MATO GROSSO DO SUL,CORUMBÁ,Pantanal,20,0.0,0.5,NaN,-20.60,-57.99
4,2020/03/12 00:03:25,GOES-16,Brasil,MATO GROSSO DO SUL,CORUMBÁ,Pantanal,14,1.9,0.8,NaN,-19.13,-57.06

In [15]:
df7 = pd.read_csv('dados/bdqueimadas_2021-03-13_2022-03-13.csv', sep = ',')

In [16]:
df7.head()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2021/03/13 00:23:14,GOES-16,Brasil,SÃO PAULO,NOVA ALIANÇA,Mata Atlântica,5,0.0,0.6,NaN,-21.08,-49.500
1,2021/03/13 01:23:06,GOES-16,Brasil,MATO GROSSO DO SUL,IVINHEMA,Mata Atlântica,8,0.0,0.7,NaN,-22.43,-53.860
2,2021/03/13 01:23:06,GOES-16,Brasil,MATO GROSSO DO SUL,IVINHEMA,Mata Atlântica,7,0.0,0.7,NaN,-22.45,-53.830
3,2021/03/13 01:23:06,GOES-16,Brasil,MATO GROSSO DO SUL,IVINHEMA,Mata Atlântica,8,0.0,0.7,NaN,-22.45,-53.860
4,2021/03/13 01:45:00,TERRA_M-M,Brasil,SÃO PAULO,TABATINGA,Cerrado,4,0.0,0.7,9.3,-21.71,-48.526

In [17]:
df8 = pd.read_csv('dados/bdqueimadas_2022-03-14_2023-03-14.csv', sep = ',')

In [18]:
df8.head()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2022/03/14 01:56:00,TERRA_M-M,Brasil,MATO GROSSO,QUERÊNCIA,Amazônia,0,9.5,0.0,5.2,-12.49238,-52.48272
1,2022/03/14 01:56:00,TERRA_M-M,Brasil,MATO GROSSO,QUERÊNCIA,Amazônia,0,9.0,0.0,3.7,-12.49110,-52.47345
2,2022/03/14 04:12:00,NOAA-20,Brasil,CEARÁ,MARACANAÚ,Caatinga,0,4.3,-999.0,1.0,-3.85479,-38.60757
3,2022/03/14 04:14:00,NOAA-20,Brasil,BAHIA,ANGICAL,Cerrado,0,0.2,0.1,1.7,-12.12732,-44.46974
4,2022/03/14 04:14:00,NOAA-20,Brasil,BAHIA,COTEGIPE,Cerrado,0,0.0,0.3,1.3,-11.97403,-44.12762

In [19]:
df9 = pd.read_csv('dados/bdqueimadas_2023-03-15_2024-03-15.csv', sep = ',')

In [20]:
df9.head()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2023/03/15 00:43:00,TERRA_M-M,Brasil,BAHIA,GUAJERU,Caatinga,2,0.00,1.00,22.9,-14.54661,-41.91785
1,2023/03/15 00:45:00,TERRA_M-M,Brasil,ALAGOAS,FLEXEIRAS,Mata Atlântica,3,5.44,0.90,14.6,-9.38301,-35.75167
2,2023/03/15 00:45:00,TERRA_M-M,Brasil,PERNAMBUCO,ALIANÇA,Caatinga,0,19.02,0.03,32.8,-7.55104,-35.18367
3,2023/03/15 00:45:00,TERRA_M-M,Brasil,PERNAMBUCO,ALIANÇA,Caatinga,0,18.99,0.03,34.9,-7.55223,-35.17761
4,2023/03/15 00:45:00,TERRA_M-M,Brasil,PERNAMBUCO,ALIANÇA,Caatinga,0,19.15,0.03,13.4,-7.55388,-35.18859

In [21]:
df10 = pd.read_csv('dados/bdqueimadas_2024-03-16_2025-03-16.csv', sep = ',')

In [22]:
df10.head()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2024/03/16 00:04:48,GOES-16,Brasil,RORAIMA,ALTO ALEGRE,Amazônia,8,0.95,0.85,69.5,3.1619,-61.7464
1,2024/03/16 00:04:48,GOES-16,Brasil,RORAIMA,ALTO ALEGRE,Amazônia,10,0.79,0.87,52.2,3.1619,-61.7275
2,2024/03/16 00:04:52,GOES-16,Brasil,RORAIMA,MUCAJAÍ,Amazônia,9,0.10,0.88,74.2,2.4135,-62.0011
3,2024/03/16 00:04:52,GOES-16,Brasil,RORAIMA,MUCAJAÍ,Amazônia,30,0.30,1.00,59.3,2.3963,-61.3802
4,2024/03/16 00:04:52,GOES-16,Brasil,RORAIMA,MUCAJAÍ,Amazônia,11,0.30,0.91,65.6,2.5047,-61.9624

In [23]:
df11 = pd.read_csv('dados/bdqueimadas_2025-03-17_2026-03-17.csv', sep = ',')

In [24]:
df11.head()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2025/03/17 00:00:00,GOES-16,Brasil,PIAUÍ,CANTO DO BURITI,Caatinga,6.0,0.00,1.00,64.9,-8.10750,-43.14110
1,2025/03/17 00:20:00,TERRA_M-M,Brasil,BAHIA,COCOS,Cerrado,24.0,0.00,1.00,33.6,-14.53482,-45.52454
2,2025/03/17 00:20:00,TERRA_M-M,Brasil,BAHIA,COCOS,Cerrado,25.0,0.00,1.00,25.4,-14.53498,-45.51424
3,2025/03/17 00:20:00,TERRA_M-M,Brasil,BAHIA,IBICOARA,Caatinga,16.0,0.00,0.78,20.2,-13.44880,-41.32147
4,2025/03/17 00:20:00,TERRA_M-M,Brasil,PIAUÍ,CORRENTE,Cerrado,5.0,25.46,0.00,31.1,-10.57658,-45.14131

In [25]:
df_final = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11], ignore_index=True)

In [26]:
df_final.head()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2016/01/01 00:00:00,GOES-13,Brasil,PARÁ,BRASIL NOVO,Amazônia,7.0,8.3,0.8,NaN,-2.95,-52.33
1,2016/01/01 00:00:00,GOES-13,Brasil,RONDÔNIA,CACOAL,Amazônia,0.0,10.6,0.1,NaN,-11.34,-61.10
2,2016/01/01 00:00:00,GOES-13,Brasil,PARÁ,VITÓRIA DO XINGU,Amazônia,7.0,7.6,0.5,NaN,-2.95,-52.31
3,2016/01/01 00:00:00,GOES-13,Brasil,RONDÔNIA,CACOAL,Amazônia,0.0,13.1,0.1,NaN,-11.34,-61.13
4,2016/01/01 00:00:00,GOES-13,Brasil,AMAZONAS,BARCELOS,Amazônia,3.0,0.0,0.9,NaN,0.50,-63.68

In [27]:
df_final.tail()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
41297534,2026/03/17 17:00:00,NPP-375,Brasil,RORAIMA,RORAINÓPOLIS,Amazônia,NaN,NaN,NaN,4.0,0.67954,-60.33555
41297535,2026/03/17 17:00:00,NPP-375,Brasil,RORAIMA,AMAJARI,Amazônia,NaN,NaN,NaN,2.7,3.55531,-61.00451
41297536,2026/03/17 17:00:00,NPP-375,Brasil,RORAIMA,CARACARAÍ,Amazônia,NaN,NaN,NaN,4.6,1.15135,-60.90672
41297537,2026/03/17 17:02:00,NPP-375,Brasil,RORAIMA,UIRAMUTÃ,Amazônia,NaN,NaN,NaN,9.7,4.69153,-60.44671
41297538,2026/03/17 17:02:00,NPP-375,Brasil,RORAIMA,AMAJARI,Amazônia,NaN,NaN,NaN,5.9,4.18497,-61.43833

In [28]:
df_final.to_csv('dados/bdqueimadas_final.csv', index=False, encoding='utf-8-sig')

In [3]:
df = pd.read_csv('dados/bdqueimadas_final.csv', sep =',')

In [4]:
df.head()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2016/01/01 00:00:00,GOES-13,Brasil,PARÁ,BRASIL NOVO,Amazônia,7.0,8.3,0.8,NaN,-2.95,-52.33
1,2016/01/01 00:00:00,GOES-13,Brasil,RONDÔNIA,CACOAL,Amazônia,0.0,10.6,0.1,NaN,-11.34,-61.10
2,2016/01/01 00:00:00,GOES-13,Brasil,PARÁ,VITÓRIA DO XINGU,Amazônia,7.0,7.6,0.5,NaN,-2.95,-52.31
3,2016/01/01 00:00:00,GOES-13,Brasil,RONDÔNIA,CACOAL,Amazônia,0.0,13.1,0.1,NaN,-11.34,-61.13
4,2016/01/01 00:00:00,GOES-13,Brasil,AMAZONAS,BARCELOS,Amazônia,3.0,0.0,0.9,NaN,0.50,-63.68

In [5]:
df.tail()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
41297534,2026/03/17 17:00:00,NPP-375,Brasil,RORAIMA,RORAINÓPOLIS,Amazônia,NaN,NaN,NaN,4.0,0.67954,-60.33555
41297535,2026/03/17 17:00:00,NPP-375,Brasil,RORAIMA,AMAJARI,Amazônia,NaN,NaN,NaN,2.7,3.55531,-61.00451
41297536,2026/03/17 17:00:00,NPP-375,Brasil,RORAIMA,CARACARAÍ,Amazônia,NaN,NaN,NaN,4.6,1.15135,-60.90672
41297537,2026/03/17 17:02:00,NPP-375,Brasil,RORAIMA,UIRAMUTÃ,Amazônia,NaN,NaN,NaN,9.7,4.69153,-60.44671
41297538,2026/03/17 17:02:00,NPP-375,Brasil,RORAIMA,AMAJARI,Amazônia,NaN,NaN,NaN,5.9,4.18497,-61.43833

In [6]:
df.describe()

,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
count,4.129546e+07,4.129546e+07,4.129546e+07,2.852548e+07,4.129754e+07,4.129754e+07
mean,1.524938e+01,7.159916e-01,-8.011276e+00,3.291033e+01,-1.009383e+01,-5.206755e+01
std,9.902524e+01,3.429551e+00,9.330984e+01,6.849916e+01,5.811838e+00,7.293606e+00
min,-9.990000e+02,0.000000e+00,-9.990000e+02,-3.800000e+00,-3.374551e+01,-7.391000e+01
25%,3.000000e+00,0.000000e+00,6.000000e-01,3.800000e+00,-1.328720e+01,-5.716859e+01
50%,8.000000e+00,0.000000e+00,1.000000e+00,9.200000e+00,-9.330000e+00,-5.137109e+01
75%,3.000000e+01,0.000000e+00,1.000000e+00,3.510000e+01,-6.339720e+00,-4.631080e+01
max,8.360000e+02,2.529800e+02,1.000000e+00,1.231130e+04,5.217610e+00,-3.479578e+01

In [7]:
df.isnull().sum()

DataHora               0
Satelite               0
Pais                   0
Estado                 0
Municipio              0
Bioma                129
DiaSemChuva         2079
Precipitacao        2079
RiscoFogo           2079
FRP             12772059
Latitude               0
Longitude              0
dtype: int64